Repository SeattleColleges/shift-app-expo, pull requests merged in 2025-02, with the labels that each got.

#67 shift-app-expo_17_66_GitHub_actions_patch
  .github/workflows/auto-assign-issues.yml
  .github/workflows/on-new-issue.yml
  post-issue-smartsheet.py
Labels: bug

#78 shift-app-expo-sprint17_ Issue#75_connect-forgot-password-with-Login-page
  app/forgot-password.tsx
Labels: Sprint 17

#77 shift-app-expo_sprint17_issue#74_connect-signup-to-login
  app/signuppage.tsx
  package-lock.json
  package.json
Labels: Sprint 17

#70 Feature 69 footer 1
  .gitignore
  app.json
  app/(auth)/forgot-password.tsx
  app/(auth)/loginpage.tsx
  app/(auth)/signuppage.tsx
  app/(tabs)/_layout.tsx
  app/(tabs)/addShift.tsx
  app/(tabs)/coworkers.tsx
  app/(tabs)/department-org.tsx
  app/(tabs)/help.tsx
  app/(tabs)/index.tsx
  app/(tabs)/notifications.tsx
  app/(tabs)/profileView.tsx
  app/_layout.tsx
  app/index.tsx
  components/Footer.tsx
  package-lock.json
Labels: Sprint 17

#84 Shift-Expo-App_17_68_remove_empty_link_component
  app/index.tsx
Labels: Sprint 17

#60 shift-app _ 16 _ 40 _ user-profile
  app/(tabs)/profileView.tsx
  components/UserDetails.tsx
  package-lock.json
Labels: Sprint 16

#83 76_add_schedule_page_sprint17_issue#76_Create-Add-Schedule-page.
  app.json
  app/add-schedule.tsx
  app/index.tsx
  components/AddSchedule.tsx
  data/locations.ts
  data/roles.ts
  data/times.ts
  package-lock.json
  package.json
Labels: Sprint 17

#92 new-style-and-updated-navigation_sprint18_issue90
  app/index.tsx
  app/request-time-off.tsx
  components/requestPage.tsx
Labels: Sprint 18

#81 Create GitHub actions
  .github/workflows/ci.yml
  .github/workflows/on-new-branch.yml
  .github/workflows/on-pull-request.yml
  .gitignore
  app-example/index.tsx
  components/ExternalLink.tsx
  components/__tests__/__snapshots__/ThemedText-test.tsx.snap
  package-lock.json
  package.json
Labels: enhancement

#94 Shift_Expo_App-18-88-login-page-links-forgot-password-signup
  app/(auth)/loginpage.tsx
Labels: enhancement, Sprint 18

#95 Shift-App-18-86-simplify notification page
  components/NotificationTile.tsx
Labels: Sprint 18

#91 89-forgot-password-page-styling_spint18_issue89
  app/(auth)/forgot-password.tsx
  package-lock.json
  package.json
Labels: Sprint 18

#93 85 shift detail page
  app/(tabs)/_layout.tsx
  app/(tabs)/shift-details-page/[id].tsx
  app/user-dashboard.tsx
  components/DayViewItem.tsx
Labels: enhancement

#103 shift-app-expo_17_82_Fix text color with dark mode on Landing Page
  app/landing.tsx
Labels: bug, Sprint 17
