Repository SeattleColleges/shift-app-expo, pull requests merged in 2025-04, with the labels that each got.

#132 shift-app-expo_20_131_Add Unit Test for CoworkersList and ExternalLink Componentsa upload
  components/__tests__/CoworkersList.test.tsx
  components/__tests__/ExternalLink.test.tsx
Labels: Sprint 20

#120 shift-app-exp_19_119_Forgot-Password-Page-Test
  app/(auth)/forgot-password.tsx
  components/__tests__/forgot-password.test.tsx
  package-lock.json
  package.json
Labels: enhancement

#116 115-signup-page-modification_sprint19_issue115
  app/(auth)/signuppage.tsx
  package-lock.json
  package.json
Labels: Sprint 19

#134 125-profile-page-component-decomposition_sprint#20_issue125
  app/(tabs)/editProfile.tsx
  app/(tabs)/images.d.ts
  app/(tabs)/profileView.tsx
  assets/images/business-man-profile-vector.jpg
  components/ProfileImage.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: Sprint 20

#133 Feature: database implementation using docker
  .env.sample
  app/(auth)/index.tsx
  app/db-function-calls.tsx
  app/index.tsx
  package-lock.json
  package.json
  supabase/.branches/_current_branch
  supabase/.gitignore
  supabase/.temp/cli-latest
  supabase/config.toml
  supabase/config/vector.toml
  supabase/db/20250327021014_data_backup.sql
  supabase/db/20250327021014_schema_backup.sql
  supabase/db/seed.sql
  supabase/migrations/20250303230523_my_.sql
  supabase/snippets/1_positions.sql
  supabase/snippets/2_departments.sql
  supabase/snippets/3_user_profiles.sql
  supabase/snippets/4_supervisor_mgmt.sql
  supabase/snippets/5_shifts.sql
  supabase/snippets/6_shift_changes_mgmt.sql
  supabase/snippets/7_roles_and_utils.sql
  supabase/snippets/profile.txt
  supabase/snippets/user_profiles.txt
Labels: enhancement, Sprint 18, Sprint 19, Sprint 20

#139 137 integrate schedule page with supabase
  app/(tabs)/index.tsx
  components/DayViewItem.tsx
  queries/getQueries.ts
  types/Shift.ts
Labels: Sprint 21

#143 Migrate Add-Shift.tsx to placeholder
  app/(tabs)/_layout.tsx
  app/(tabs)/add-shift.tsx
  app/(tabs)/addShift.tsx
  app/add-schedule.tsx
  components/AddShift.tsx
Labels: good first issue, Sprint 21
