Repository SeattleColleges/shift-app-expo, pull requests merged in 2025-01, with the labels that each got.

#37 Co workers page placeholder
  app/co-workers.tsx
Labels: Sprint 15

#18 shift-app_spring-15_issue-17_Admin-Dashboard
  .gitignore
  app/admin.tsx
  assets/images/profileImg.jpg
  components/Footer.tsx
  package-lock.json
Labels: Sprint 15

#39 shift-app-expo_15_38_user-dashboard-page
  app/user-dashboard.tsx
  package-lock.json
  package.json
Labels: Sprint 15

#36 shift-app-expo_15_21_forgot-password-placeholder-page
  .idea/.gitignore
  app/forgot-password.tsx
  app/index.tsx
  package-lock.json
  package.json
  supabaseClient.js
Labels: Sprint 15

#14 shift-app-expo_sprint14_issue#13_Readme-update
  README.md
  package-lock.json
Labels: Sprint 14

#47 shift-app-expo_16_46_smartsheets_fix
  post-issue-smartsheet.py
Labels: bug

#50 shift-app-expo_16_46_smartsheets_fix_2
  post-issue-smartsheet.py
Labels: bug

#54 shift-app-expo_16_53_smartsheets_fix
  post-issue-smartsheet.py
Labels: bug

#43 42 coworkers page component
  app/co-workers.tsx
  app/index.tsx
  components/CoworkerListItem.tsx
  components/CoworkersList.tsx
  components/ThemedText.tsx
  data/dummyCoworkerData.ts
Labels: Sprint 16

#23 shift-app-expo_sprint15_issue#20_Create-Login-Signup-page
  .idea/.gitignore
  .idea/modules.xml
  .idea/shift-app-expo.iml
  .idea/vcs.xml
  .idea/workspace.xml
  app-example/(tabs)/_layout.tsx
  app-example/(tabs)/explore.tsx
  app-example/(tabs)/index.tsx
  app-example/+html.tsx
  app-example/+not-found.tsx
  app-example/_layout.tsx
  app-example/index.tsx
  app/_layout.tsx
  app/index.tsx
  app/loginpage.tsx
  app/signuppage.tsx
  package.json
Labels: Sprint 15

#61 shift-app-expo_16_59_notifications_page_component
  app/index.tsx
  app/notifications.tsx
  components/NotificationTile.tsx
  data/dummyNotificationData.ts
Labels: Sprint 16

#65 64 user dashboard 1 make component from toggle button
  app/index.tsx
  app/user-dashboard.tsx
  components/dashboard/OptionToggle.tsx
Labels: Sprint 17
