Repository SeattleColleges/shift-app-expo, pull requests merged in 2025-03, with the labels that each got.

#109 106-request-time-off update_sprint19_#106
  components/DatePickerComponent.tsx
  components/requestPage.tsx
  components/showAlert.tsx
Labels: Sprint 19

#107 104 edit profile page
  app/(tabs)/_layout.tsx
  app/(tabs)/editProfile.tsx
  app/(tabs)/profileView.tsx
  components/CustomInputFields.tsx
  components/UserDetails.tsx
  constants/Colors.ts
Labels: enhancement, Sprint 19

#102 Migrate user-dashboard into default tabbed view
  app/(tabs)/index.tsx
  app/index.tsx
  app/user-dashboard.tsx
  package-lock.json
  tsconfig.json
Labels: enhancement, Sprint 18

#114 shift_app_repo_19_110_login_button_and_tests
  app/(auth)/loginpage.tsx
  components/__tests__/LoginButton-test.tsx
Labels: enhancement, Sprint 19

#128 Shift_App_Exp_20_123_Detail-Page-Arrow_Navigation
  app/(tabs)/shift-details-page/[id].tsx
  app/shift-navigation.tsx
Labels: enhancement, Sprint 20

#112 Experiment auth implementation
  app-example/index.tsx
  app.json
  app/(auth)/_layout.tsx
  app/(auth)/forgot-password.tsx
  app/(auth)/index.tsx
  app/(auth)/signuppage.tsx
  app/(tabs)/index.tsx
  app/index.tsx
  app/landing.tsx
  app/user-dashboard.tsx
  components/__tests__/LoginButton-test.tsx
  lib/supabaseClient.ts
  package-lock.json
  package.json
  supabase/snippets/profile.txt
  supabaseClient.js
Labels: Sprint 18

#113 Auth Implementation: Local Supabase Instance
  app.json
  package-lock.json
  package.json
  supabase/config.toml
  supabase/db/seed.sql
  supabase/migrations/20250303230523_my_.sql
  supabase/snippets/user_profiles.txt
Labels: Sprint 19
